const fs = require('fs');
let lines = fs.readFileSync('src/components/UI.jsx', 'utf8').split('\n').slice(0, 250);
lines.push(`export const TypewriterText = ({ text, delay = 80 }) => {`);
lines.push(`  const [content, setContent] = useState('');`);
lines.push(`  `);
lines.push(`  useEffect(() => {`);
lines.push(`    let index = 0;`);
lines.push(`    const interval = setInterval(() => {`);
lines.push(`      setContent(text.substring(0, index + 1));`);
lines.push(`      index++;`);
lines.push(`      if (index >= text.length) clearInterval(interval);`);
lines.push(`    }, delay);`);
lines.push(`    return () => clearInterval(interval);`);
lines.push(`  }, [text, delay]);`);
lines.push(``);
lines.push(`  return (`);
lines.push(`    <>`);
lines.push(`      {content}`);
lines.push(`      <span className="animate-pulse ml-0.5 opacity-70 text-emerald-400">_</span>`);
lines.push(`    </>`);
lines.push(`  );`);
lines.push(`};`);
fs.writeFileSync('src/components/UI.jsx', lines.join('\n'));
